# Generated by Django 6.0.4 on 2026-04-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_genresearchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=100)),
                ('movie_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
