# Generated by Django 6.0.4 on 2026-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_movierating'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField(unique=True)),
                ('genre_name', models.CharField(max_length=100)),
                ('total_movies', models.IntegerField(default=0)),
                ('avg_popularity', models.FloatField(default=0.0)),
                ('avg_vote_average', models.FloatField(default=0.0)),
                ('total_vote_count', models.IntegerField(default=0)),
                ('highest_popularity', models.FloatField(default=0.0)),
                ('lowest_popularity', models.FloatField(default=0.0)),
                ('latest_release_date', models.DateField(blank=True, null=True)),
                ('oldest_release_date', models.DateField(blank=True, null=True)),
                ('most_common_language', models.CharField(blank=True, max_length=20, null=True)),
                ('most_common_country', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
